"""Add extended complaint fields

Revision ID: 40470a4fb285
Revises: cc64648fd77e
Create Date: 2026-07-27 11:14:51.938609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40470a4fb285'
down_revision: Union[str, None] = 'cc64648fd77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('product_strength', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('manufacturing_date', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('expiry_date', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('quantity_affected', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('complaint_date', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('complaint_type', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('complaint_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'complaint_source')
    op.drop_column('complaints', 'complaint_type')
    op.drop_column('complaints', 'complaint_date')
    op.drop_column('complaints', 'quantity_affected')
    op.drop_column('complaints', 'expiry_date')
    op.drop_column('complaints', 'manufacturing_date')
    op.drop_column('complaints', 'batch_number')
    op.drop_column('complaints', 'product_strength')
    # ### end Alembic commands ###
